config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  devise_for :users
  resources :blog_posts do
    get "pub", on: :collection
    # resources :likes
  end

  post "/blog_posts/:id/like", to: "likes#create", as: :new_blog_post_like
  delete "/blog_posts/:id/destroy_like", to: "likes#destroy", as: :destroy_blog_post_like


  # Defines the root path route ("/")
  root "blog_posts#index"

  # get "/blog_posts/new", to: "blog_posts#new", as: :new_blog_post
  # get "/blog_posts/:id/edit", to: "blog_posts#edit", as: :edit_blog_post

  # get "/blog_posts/:id", to: "blog_posts#show", as: :blog_post
  # patch "/blog_posts/:id", to: "blog_posts#update"
  # delete "/blog_posts/:id", to: "blog_posts#destroy"

  # post "/blog_posts", to: "blog_posts#create", as: :blog_posts
 
  # blog_post_path(1) -> "/blog_posts/1"
  # blog_post_url(1) -> "localhost:3000/blog_posts/1"
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord

  has_many :likes, dependent: :destroy
  has_rich_text :content

  validates :title, presence: true, length: {maximum: 35}
  validates :content, presence: true

  scope :sorted, -> {order(arel_table[:published_at].desc.nulls_first).order(updated_at: :desc)}
  scope :search, ->(text) {sorted.where("title like ?", "%"+text.to_s+"%")
  .or(sorted.where("UID like ?", "%"+text.to_s+"%"))
  .or(sorted.where("UID like ?", User.where("username like ?", "%"+text.to_s+"%").ids[0]))}
  # scope :sorted, -> {order(published_at: :desc, updated_at: :asc)}
  scope :draft, -> {where(published_at: nil)}
  scope :published, -> {where("published_at <= ?", Time.current)}
  scope :scheduled, -> {where("published_at > ?", Time.current)}

  def draft?
    published_at.nil?
  end
  
  def scheduled?
    published_at? && published_at > Time.current
  end

  def private?
    public? == false
  end

  def edited?
    published_at? && created_at < updated_at - 1.minute
  end

  # def liked_by?(blog_post, currentuser)
  #   if currentuser.liked_posts != nil
  #     users_liked_posts = currentuser.liked_posts.split(',')
  #     blog_post_id = blog_post.id.to_s
  #     users_liked_posts.include?(blog_post_id)
  #   else
  #     return false
  #   end
  # end

  # def like(blog_post, currentuser)
  #   if !users_liked_posts = currentuser.liked_posts.split(',')
  #     users_liked_posts = ""
  #   end
  #   liked_posts = currentuser.liked_posts.to_s
  #   blog_post_id = blog_post.id.to_s
  #   if !users_liked_posts.include?(blog_post_id)
  #     likes = blog_post.likes
  #     blog_post.likes += 1
  #     if blog_post.save(touch: false)
  #       User.where(id: currentuser.id).update(liked_posts: liked_posts+blog_post_id+",")
  #     end
  #   else
  #     blog_post.unlike(blog_post, currentuser, blog_post_id, users_liked_posts)
  #   end
  # end

  # def unlike(blog_post, currentuser, blog_post_id, users_liked_posts)
  #   if users_liked_posts.delete(blog_post_id)
  #     if users_liked_posts.length === 1
  #       users_updated_liked_posts = users_liked_posts.join(",").to_s + ","
  #     else
  #       users_updated_liked_posts = users_liked_posts.join(",")
  #     end
  #     likes = blog_post.likes
  #     if blog_post.update(likes: likes -= 1)
  #       User.where(id: currentuser.id).update(liked_posts: users_updated_liked_posts)
  #     end
  #   end
  # end
end

# BlogPosts.all
# BlogPosts.draft
# BlogPosts.published
# BlogPosts.scheduled

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :get_user_id, only: [:index, :show]
  before_action :set_blog_post, only: [:show, :edit, :update, :destroy]
  
  def index
    @blog_posts = BlogPost.sorted
    @published_blog_posts = BlogPost.published.sorted.search(params[:search])
    @searched_blog_posts = BlogPost.sorted.search(params[:search])
    
    if user_signed_in?
      @Pagy, @blog_posts = pagy(@searched_blog_posts.where(UID: @current_user.id))
    else
      @Pagy, @blog_posts = pagy(@published_blog_posts.where(public: true))
    end
  rescue Pagy::OverflowError
    redirect_to root_path(page: 1)
  end

  def pub
    @searched_blog_posts = BlogPost.published.search(params[:search])

    @Pagy, @blog_posts = pagy(@searched_blog_posts.where(public: true)) 
  rescue Pagy::OverflowError
    redirect_to pub_blog_posts_path(page: 1)
  end

  # def like
  #   @blog_post.like(@blog_post, @current_user)

  #   render partial: "likes", locals: {blog_post: @blog_post}, content_type: "text/html", status: 500
  # end

  def show
    @blog_UID = @blog_post.UID
    @username = User.find(@blog_UID).username
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path
  end

  def new
    @blog_post = BlogPost.new
  end

  def edit
    if @current_user.id != @blog_post.UID
      redirect_to root_path
    end
  end

  def update
    if @blog_post.update(blog_post_params)
      redirect_to @blog_post
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @blog_post.destroy()
      redirect_to root_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def create
    @blog_post = BlogPost.new(blog_post_params)
    if @blog_post.save
      redirect_to @blog_post
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def get_user_id
    return unless session[:user_id]
    @current_user ||= User.find(session[:user_id])
  end

  def blog_post_params
    params.require(:blog_post).permit(:title, :content, :published_at, :UID, :public)
  end

  def set_blog_post
    @blog_post = user_signed_in? ? BlogPost.find(params[:id]) : BlogPost.published.find(params[:id])
  rescue  ActiveRecord::RecordNotFound
    redirect_to root_path
  end
end

app/views/blog_posts/_blog_index.html.erb
<% if user_signed_in? %>
    <% if current_page?(root_path) || !current_page?(pub_blog_posts_path) %>
        <h1 class="page-header"><span class="selected">My blog</span><span style="font-weight: 200;"class="line"> | </span> <%= link_to "Public blog", pub_blog_posts_path, class: "not_selected" %></h1>
    <% else %>
        <h1 class="page-header"><%= link_to "My blog", root_path, class: "not_selected" %> <span style="font-weight: 200;"class="line"> | </span><span class="selected">Public blog</span></h1>
    <% end %>
<% else %>
    <h1 class="page-header"><span class="selected">Public blog</span></h1>
<% end %>
<% if @blog_posts.length > 0 %>
    <% @blog_posts.each do |blog_post| %>
        <div class="BlogBox rounded-md <%=blog_post_colour(blog_post, current_page?(pub_blog_posts_path), current_user)%>">
            <h5 style="display:flex;place-self:flex-start;margin:0px;padding:0px;">Likes: <%= blog_post.likes.count %></h5>
            <% if blog_post.draft? %><h3 class="text-red-400 BlogBoxTitle">Draft:</h3><% end %>
            <% if blog_post.scheduled? %><h3 class="text-blue-400 BlogBoxTitle">Scheduled for: <%= blog_post.published_at %></h3><% end %>
            <div class="private-icon" style="display:flex;flex-direction:column-reverse;align-items:flex-end;">
            <% if blog_post.private? %><i class="fa-solid fa-lock"></i><% end %> 
            <% if blog_post.edited? %><i class="fa-regular fa-pen-to-square"> edited</i><% end %>
            </div>

            <h5 style="position:absolute;" class="time-stamp"> <%= blog_post.published_at.to_s[0,10] %> </h5>
            <h2 class="BlogBoxTitle" ><%= link_to blog_post.title, blog_post %></h2>
            <%= blog_post.content %>
        </div>
    <% end %>

    <%== pagy_nav(@Pagy) if @Pagy.pages > 1 %>
<% else %>
    <h3 style="color:rgb(180,180,180);font-weight:300;">Create and upload a blog post to view it here...</h3>
<% end %>

app/views/blog_posts/_form.html.erb
<%= form_with model: @blog_post do |form| %>
    <% if form.object.errors.any? %>
        <div>
            <% form.object.errors.full_messages.each do |message| %>
                <div><%= message %></div>
            <% end %>
        </div>
    <% end %>

    <div>
        <%= form.label :title %>
        <%= form.text_field :title %>

        <%= form.label :public %>
        <%= form.check_box :public %>
    </div>

    <div>
        <%= form.label :content %>
        <%= form.rich_text_area :content, class: "topmargin", style: "text-align: center;display: inline-block;width: 100%;overflow: hidden;" %>
    </div>

    <div>
        <%= form.label :published_at %>
        <%= form.datetime_select :published_at, include_blank: true, selected: @blog_post.published_at || Time.current %>
                                   
        <%# form.date_select(:published_at, include_blank: true, selected: Date.current, start_year: Date.today.year - 100, end_year: Date.today.year - 18) %>
        
    </div>

    <%= form.number_field :UID, value: current_user.id, style: "opacity: 0%;display: none;" %>

    <%= form.button :submit_btn, class: "joes_button topmargin" %>
<% end %>

<%# banana %>

app/views/blog_posts/_likes.html.erb

<% pre_like = @blog_post.likes.find { |like| like.user_id == current_user.id} %>
<%= turbo_frame_tag @blog_post, :likes do %>
    Likes: <%= @blog_post.likes.count %>
    <% if pre_like %>
        <%= button_to "Unlike", destroy_blog_post_like_path(@blog_post), method: :delete, class: "joes_button" %>
    <% else %>
        <%= button_to "Like", new_blog_post_like_path(@blog_post), method: :post, class: "joes_button" %>
    <% end %>
<% end %>

app/views/blog_posts/edit.html.erb
<h1>Edit blog post</h1>

<%= render partial: "form", locals: {blog_post: @blog_post} %>
<div class="edit-btn">
    <%= button_to "Delete", @blog_post, method: :delete, data: {turbo_confirm: "Are you sure?"}, class: "joes_button" %>
    <%= button_to "Cancel", blog_post_path, method: :get, class: "joes_button" %>
</div>

app/views/blog_posts/index.html.erb
<% session[:index] = true %>
<div>
    <%= form_with url: root_path, method: :get, html: {class: "search-form"} do |form| %>

        <%= form.label :search, "Search:   " %>
        <%= form.text_field :search %>
        <%= form.submit "Search", class: "joes_button topmargin" %>

    <% end %>
</div>
<%= render partial: "blog_index" %>

app/views/blog_posts/new.html.erb
<h1 style="padding-top: 100px;" >New blog post</h1>


<%= render partial: "form", locals: {blog_post: @blog_post} %>

app/views/blog_posts/pub.html.erb
<% session[:index] = false %>
<div>
    <%= form_with url: "/blog_posts/pub", method: :get, html: {class: "search-form"} do |form| %>

        <%= form.label :search, "Search:   " %>
        <%= form.text_field :search %>
        <%= form.submit "Search", class: "joes_button topmargin" %>

    <% end %>
</div>
<%= render partial: "blog_index" %>

app/views/blog_posts/show.html.erb
<% if @current_user.id == @blog_UID %>
    <%= button_to "Edit blog", edit_blog_post_path(@blog_post), method: :get, class: "joes_button", style: "margin-top: 50px;" if user_signed_in? %>
<% end %>

<div style="text-align: center;display: flex;justify-content: center;flex-direction: column;align-content: center;flex-wrap: wrap;">
    <h1><%= @blog_post.title %></h1>

    <h3><%= @blog_post.content %></h3>
</div>

<div class="rounded-md <%=blog_post_colour(@blog_post, current_page?(blog_post_path), @current_user)%>">
    <h4 class="<%=blog_post_colour(@blog_post, current_page?(blog_post_path), @current_user)%>">
        <%= !@blog_post.draft? ? !@blog_post.scheduled? ? "Published at: "+ @blog_post.published_at.to_s : "Scheduled for: "+ @blog_post.published_at.to_s : "Draft" %>
        <% if @blog_post.draft? %>
            <%= button_to "Delete", @blog_post, method: :delete, data: {turbo_confirm: "Are you sure?"}, class: "joes_button_red" %>
        <% end %>
        <p>
            Public: <%= @blog_post.public %>
        </p>
        <%= render partial: "likes" %>
        <p>
            By: <%= @username %>
        </p>
    </h4>
</div>
