config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  devise_for :users
  resources :blog_posts do
    get "pub", on: :collection
    # resources :likes
  end

  post "/blog_posts/:id/like", to: "likes#create", as: :new_blog_post_like
  delete "/blog_posts/:id/destroy_like", to: "likes#destroy", as: :destroy_blog_post_like


  # Defines the root path route ("/")
  root "blog_posts#index"

  # get "/blog_posts/new", to: "blog_posts#new", as: :new_blog_post
  # get "/blog_posts/:id/edit", to: "blog_posts#edit", as: :edit_blog_post

  # get "/blog_posts/:id", to: "blog_posts#show", as: :blog_post
  # patch "/blog_posts/:id", to: "blog_posts#update"
  # delete "/blog_posts/:id", to: "blog_posts#destroy"

  # post "/blog_posts", to: "blog_posts#create", as: :blog_posts
 
  # blog_post_path(1) -> "/blog_posts/1"
  # blog_post_url(1) -> "localhost:3000/blog_posts/1"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Blog" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="turbo-prefetch" content="false">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "actiontext", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  </head>

  <body class="prose mx-auto text-center mb-7">

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div class="top-menu-small">
      <i id="bars" class="fa-solid fa-bars nyc-bars nyc-bg-yellow" onclick="show()"></i>
    </div>

    <div class="top-menu" id="top-menu">
      <% if session[:index] %>
        <%= button_to "Home", root_path, method: :get, class: "joes_button" %>
      <% else %>
        <%= button_to "Home", pub_blog_posts_path, method: :get, class: "joes_button" %>
      <% end %>
      <% if user_signed_in? %>
        <%= button_to "Log out", destroy_user_session_path, method: :delete, class: "joes_button" %>
        <%= button_to "Profile", edit_user_registration_path, method: :get, class: "joes_button" %>
        <%= button_to "New blog", new_blog_post_path, method: :get, class: "joes_button" %>
      <% else %>
        <%= button_to "Log in", new_user_session_path, method: :get, class: "joes_button" %>
        <%= button_to "Sign up", new_user_registration_path, method: :get, class: "joes_button" %>
      <% end %>
      <i id="X-mobile" class="fa-regular fa-circle-xmark" onclick="hide()"></i>

    </div>

    <%= yield %>

  </body>
</html>